name: 'WIP Label'
description: 'Blocks a PR when a label is present.'
inputs:
  label:
    description: 'label(s) for which to block the PR'
    required: true
  allowed_base:
    description: 'base ref(s) where the PR will not be locked'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
